import * as THREE from 'three';
import { load3DModelFromUrl, load3DModelFromObjText, load3DModelFromGlbBuffer } from './model3DLoader';

export interface RiggedTransform {
  position: [number, number, number];
  rotationDeg: [number, number, number];
  scale: [number, number, number];
}

export interface CustomRiggedItem {
  id: string;
  name: string;
  category: 'hair' | 'hat' | 'accessory';
  attachTo: 'head' | 'torso' | 'leftArm' | 'rightArm' | 'leftLeg' | 'rightLeg';
  transform: RiggedTransform;
  fileFormat: 'obj' | 'glb' | 'gltf';
  fileName: string;
  fileUrl: string;
  colorTint: string | null;
  description?: string;
  previewColor?: string;
  creator?: string;
}

// ----------------------------------------------------
// BoBlox Accessory Definition: blue hair for blue individuals
// Generated by Rigging Tool for probablynot
// ----------------------------------------------------
export const CUSTOM_ITEM_BLUE_HAIR_FOR_BLUE_INDIVIDUALS: CustomRiggedItem = {
  id: 'blue_hair_for_blue_individuals',
  name: 'blue hair for blue individuals',
  category: 'hair',
  attachTo: 'head',
  transform: {
    position: [0.0, -4.65, 0.0],
    rotationDeg: [0.0, 0.0, 0.0],
    scale: [2.0, 2.0, 2.0],
  },
  fileFormat: 'obj',
  fileName: 'blue_hair_for_blue_individuals.obj',
  fileUrl: '/models/blue_hair_for_blue_individuals.obj',
  colorTint: '#3b82f6',
  description: 'Custom fitted blue hairstyle with exact calibrated position',
  previewColor: '#3b82f6',
  creator: 'probablynot',
};

// ----------------------------------------------------
// BoBlox Accessory Definition: transparent red roblox hair
// Generated by Rigging Tool for probablynot
// ----------------------------------------------------
export const CUSTOM_ITEM_TRANSPARENT_RED_ROBLOX_HAIR: CustomRiggedItem = {
  id: 'transparent_red_roblox_hair',
  name: 'transparent red roblox hair',
  category: 'hair',
  attachTo: 'head',
  transform: {
    position: [0.02, 0.56, 0.06],
    rotationDeg: [0.0, -180.0, 0.0],
    scale: [1.1, 1.1, 1.1],
  },
  fileFormat: 'glb',
  fileName: 'transparent_red_roblox_hair.glb',
  fileUrl: '/models/transparent_red_roblox_hair.glb',
  colorTint: null,
  description: 'Transparent red aesthetic roblox hair',
  previewColor: '#ef4444',
  creator: 'probablynot',
};

// ----------------------------------------------------
// BoBlox Accessory Definition: roblox hair2
// Generated by Rigging Tool for probablynot
// ----------------------------------------------------
export const CUSTOM_ITEM_ROBLOX_HAIR2: CustomRiggedItem = {
  id: 'roblox_hair2',
  name: 'roblox hair2',
  category: 'hair',
  attachTo: 'head',
  transform: {
    position: [0.02, 0.56, 0.06],
    rotationDeg: [0.0, -180.0, 0.0],
    scale: [1.1, 1.1, 1.1],
  },
  fileFormat: 'glb',
  fileName: 'roblox_hair2.glb',
  fileUrl: '/models/roblox_hair2.glb',
  colorTint: null,
  description: 'Custom fitted roblox hair accessory 2',
  previewColor: '#f97316',
  creator: 'probablynot',
};

/**
 * Registry of all user-submitted custom rigged items
 */
export const REGISTERED_CUSTOM_ITEMS: CustomRiggedItem[] = [
  CUSTOM_ITEM_BLUE_HAIR_FOR_BLUE_INDIVIDUALS,
  CUSTOM_ITEM_TRANSPARENT_RED_ROBLOX_HAIR,
  CUSTOM_ITEM_ROBLOX_HAIR2,
];

// Cache of loaded raw 3D groups to avoid fetching multiple times
const modelGroupCache = new Map<string, THREE.Group>();

/**
 * Loads and builds the THREE.Group for a registered custom item with its exact calibrated transforms.
 */
export async function loadCustomRiggedItemMesh(
  item: CustomRiggedItem,
  tintOverride?: string | null
): Promise<THREE.Group> {
  const cacheKey = `${item.id}_${tintOverride || item.colorTint || 'default'}`;

  // Check if we have raw group loaded
  let baseGroup = modelGroupCache.get(item.fileUrl);
  if (!baseGroup) {
    const loaded = await load3DModelFromUrl(item.fileUrl, item.fileFormat);
    baseGroup = loaded.group;
    modelGroupCache.set(item.fileUrl, baseGroup);
  }

  // Clone so multiple instances or transforms don't collide
  const group = baseGroup.clone(true);

  // Apply color tint if applicable (for OBJ or meshes that accept tint)
  const activeTint = tintOverride || item.colorTint;
  if (activeTint) {
    const tintColor = new THREE.Color(activeTint);
    group.traverse((child) => {
      if (child instanceof THREE.Mesh) {
        if (Array.isArray(child.material)) {
          child.material = child.material.map((m) => {
            const newMat = m.clone();
            if ('color' in newMat) (newMat as THREE.MeshStandardMaterial).color.copy(tintColor);
            return newMat;
          });
        } else if (child.material) {
          const newMat = child.material.clone();
          if ('color' in newMat) (newMat as THREE.MeshStandardMaterial).color.copy(tintColor);
          child.material = newMat;
        }
      }
    });
  }

  // Apply EXACT calibrated transform
  const container = new THREE.Group();
  container.name = `custom_rigged_${item.id}`;

  group.position.set(
    item.transform.position[0],
    item.transform.position[1],
    item.transform.position[2]
  );
  group.rotation.set(
    THREE.MathUtils.degToRad(item.transform.rotationDeg[0]),
    THREE.MathUtils.degToRad(item.transform.rotationDeg[1]),
    THREE.MathUtils.degToRad(item.transform.rotationDeg[2])
  );
  group.scale.set(
    item.transform.scale[0],
    item.transform.scale[1],
    item.transform.scale[2]
  );

  container.add(group);
  return container;
}
